### ISSUE TITLE
Something went wrong, trying again

### ISSUE THREAD

**Issue by grenaud** [mailund/admixture_graph#18]
Hello! I am trying to run fit_graph. 

I have:

```
 head(dstat)
     W    X    Y    Z       D Z.value
1 gp1 gp2 gp3 gp4  0.0068   1.698

```
I essentially have all possible dstats.

and I use:

```

dsubsample<-filter_on_leaves(dstat,unadmix_graph) 

graph_fit <- fit_graph(unadmix_graph, dsubsample )

```

As suggested by one of the issues, I still get:
```

Something went wrong, trying again.
Error: C stack usage  7969252 is too close to the limit
```

Any clue why?

**Comment by KalleLeppala** [comment]
Hi Gabriel,
it's probably because there are leaves in the graph that don't appear in data. I should really make an update one of these days because that trap has caught so many users.
Kalle

**Comment by grenaud** [comment]
Hi Kalle,
Thanks for the answer! I am in Aarhus and can pass by if you want to see my code. Normally, I ran every possible d-stat as I have few very groups.

cheers,

Gabriel

**Comment by KalleLeppala** [comment]
I'm on my way to Finland for the weekend but I'll be happy to help you once
I get back on Monday.
Kalle

**Comment by KalleLeppala** [comment]
Did you manage to solve the problem?

**Comment by grenaud** [comment]
Hi Kalle, sorry for the lack of feedback. I haven't tried again however the paper is almost submitted so depending on what extra analyses the reviewers might ask for, I might rerun it again. For now you can close this issue.

**Comment by KalleLeppala** [comment]
Okay, good luck with the paper!
