### ISSUE TITLE
orientation of Cholesky factor

### ISSUE THREAD

**Issue by nspope** [mailund/admixture_graph#19]
Hi, looking at the source it seems that the Cholesky factor passed as the "concentration" argument in `fit_graph` should be the upper, not lower, triangular factor. Can you please confirm? Thanks.

**Comment by KalleLeppala** [comment]
Yes it looks right, I can't believe I only wrote "Cholesky decomposition" in the documentation.

**Comment by nspope** [comment]
Thanks. May I recommend an explicit check for an upper triangular matrix, along the lines of
```
all(abs(concentration[upper.tri(concentration)]))
```
this is an easy mistake to make, and would make the results bogus.

**Comment by nspope** [comment]
Sorry, I'm writing to quickly ... what I mean by explicit check is
```
all(abs(concentration[upper.tri(concentration,diag=TRUE)])) & !any(abs(concentration[lower.tri(concentration)]))
```

**Comment by KalleLeppala** [comment]
It's a good suggestion, and the documentation should be clearer on what the input should be. It doesn't really even need to be triangular, just any C such that C^T*C = Sigma^(-1). By the way in the data we studied when developing the package (baboons) didn't have Sigma matrix or the concentration matrix, as the F-statistics were generated with Patterson's package, so we only used the diagonal proxy made from the z-scores. Patterson and/or Reich said in one of their papers that using the Sigma^(-1) matrix is unstable, and this is the reason for their choice of the diagonal proxy matrix. We wanted to provide the functionality anyway and I don't see why using Sigma^(-1) would be unstable, but be warned. By the way I have some python code here in github, f_stats.py, that calculates f-statistics and the concentration inputs for the use of admixturegraph. I haven't touched it in a long time as I've moved on to doing different stuff (I really should get back to at least make an update to admixturegraph), but I think it's mostly documented. No one has used it for actual science yet but if you feel adventurous, take a look :)

**Comment by nspope** [comment]
Thanks. Yes, any matrix square root would work -- orientation of the Cholesky factor is still important though, because if misoriented it is not a matrix square root (or rather, is square root of the wrong matrix). 

The instability issue is due to a high degree of covariance between f2 branch lengths, and the fact that the covariance matrix is calculated from a relatively small number of bootstrap samples given the n choose 2 linearly independent statistics-- so is usually very poorly conditioned. In practice what I have been doing is using a shrinkage estimator (Shafer and Strimmer 2005 Statistical Applications in Genetics), that shrinks towards a diagonal target, and always returns a well-conditioned matrix. At least with my data, using this rather than a strictly diagonal approximation seems to matter quite alot.

Anyhow, I'll close this, thanks for the package.
Nate
